### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by aidanheerdegen** [coecms/dusql#14] opened 2019-03-06 21:57 UTC
I tried to scan my `v45` `short` directory and the process was killed due to exceeding the 2GB interactive memory limit

```
$ dusql scan /short/v45/aph502/
Directories Scanned: 72223it [07:10, 125.72it/s]
RSS exceeded.user=aph502, pid=21266, cmd=python, rss=2251572, rlim=2097152
Killed
```
That directory is about 2.5TB with 1.15M nodes.

Are there recommended limits on what can be scanned effectively? Could this memory usage be reduced, or is that just the in-memory SQL table about which nothing much can be done?

**Comment by ScottWales** [comment] 2019-03-06 23:13
I can't reproduce- have currently scanned approx 600,000 inodes from your directory without issue.

Where are you running this from (what disk - /short, /home, /g/data)

What version are you using? `python -c 'import dusql; print(dusql.__version__)'`

**Comment by aidanheerdegen** [comment] 2019-03-07 00:52
Odd. I tried again in `/tmp` in case I was running out of space
```
$ python -c 'import dusql; print(dusql.__version__)'
0.2
$ which dusql
/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.01/bin/dusql
```
```
$ /usr/bin/time -v dusql scan /short/v45/aph502/                                                                  
Directories Scanned: 72223it [01:50, 682.66it/s] 
RSS exceeded.user=aph502, pid=6195, cmd=python, rss=2458840, rlim=2097152
Command terminated by signal 9
        Command being timed: "dusql scan /short/v45/aph502/"
        User time (seconds): 10.42
        System time (seconds): 74.28
        Percent of CPU this job got: 64%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 2:12.15
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 2464748
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 1312548
        Voluntary context switches: 707739
        Involuntary context switches: 10303
        Swaps: 0
        File system inputs: 0
        File system outputs: 280
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

**Comment by ScottWales** [comment] 2019-03-07 01:34
Thanks, can you please try the version in the `clef-test` environment, that should contain the fix for this issue

**Comment by aidanheerdegen** [comment] 2019-03-07 04:25
Yeah that worked
```
$ /usr/bin/time -v dusql scan /short/v45/aph502/                                                                                               
Directories Scanned: 1168601it [44:23, 438.78it/s] 
        Command being timed: "dusql scan /short/v45/aph502/"
        User time (seconds): 128.36
        System time (seconds): 174.01
        Percent of CPU this job got: 11%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 44:25.76
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 237472
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 7004420
        Voluntary context switches: 907752
        Involuntary context switches: 17765
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```
Thanks

**Closed as completed** 2020-08-26 05:18 UTC
